version: '3.8'
services:
  gov-watcher-be:
    image: dlaudfuf33/gov-watcher-be:latest
    container_name: gov-watcher-be
    restart: always
    environment:
      DB_URL: "${DB_URL}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      SPRING_PROFILES_ACTIVE: "${SPRING_PROFILES_ACTIVE}"
    ports:
      - "8080:8080"
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external: true