
spring:
  application:
    name: gov-watcher
  datasource:
    url: jdbc:mysql://localhost:3306/gwatch?serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password: dkrakek1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none   # 또는 update / validate / create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  # optional: 타임존 에러 방지용
  jackson:
    time-zone: Asia/Seoul